ADD Tinymce editor
Som-Energia/uiqmako-ui pull request #11
Opened 2022-08-26 07:34 UTC by xavierteres

**Que vol resoldre aquesta PR:**

L'editor SunEditor donava problemes amb el format de l'HTML.

**Comportament antic:**

El SunEditor trancava el format de moltes plantilles.

**Comportament nou:**

S'ha substituit el SunEditor per TinyMCE.

**Targeta on es demana:**

https://trello.com/c/BfXuf4zN/5282-0-0-p22-ep263-ui-qmako-suneditor-genera-paragrafs-extra

2022-08-29 23:17 UTC, vokimon commented
Maybe you already thought about  it but just in case. There is a OS  TinyMCE plugin could be ideal to get a single editor for the whole template instead of having one editor for each html fragment between python fragments, Just by making non editable the python fragments:. 
https://www.tiny.cloud/docs/plugins/opensource/noneditable/

2022-08-30 11:57 UTC, xavierteres commented
> Maybe you already thought about it but just in case. There is a OS TinyMCE plugin could be ideal to get a single editor for the whole template instead of having one editor for each html fragment between python fragments, Just by making non editable the python fragments:. https://www.tiny.cloud/docs/plugins/opensource/noneditable/

We have tried it. We think that it will not work for us because it adds HTML tags to the Python code and brokes it.

2022-09-07 09:14 UTC, MarJene requested changes

2022-09-07 09:14 UTC, MarJene commented on README.md
> +### `npm postinstall`
```suggestion
### `npm run postinstall`
```

2022-09-08 01:20 UTC, vokimon commented
> > Maybe you already thought about it but just in case. There is a OS TinyMCE plugin could be ideal to get a single editor for the whole template instead of having one editor for each html fragment between python fragments, Just by making non editable the python fragments:. https://www.tiny.cloud/docs/plugins/opensource/noneditable/
> 
> We have tried it. We think that it will not work for us because it adds HTML tags to the Python code and brokes it.

Afterthought: If you can get to the "do not edit" behaviour for the code, then you are not interested at all in which ever changes the editor returns. Just add the 'donotedit' tag and also an ID to recover the original python after the edition. Could that work? Of course, not for this PR.

2022-09-08 09:22 UTC, merged